# Tenants Configuration
# Add new tenants here and restart the application to sync them

tenants:
  - name: "Project Alpha"
    domain: "alpha.com"
    settings:
      otp_enabled: true
      session_timeout_minutes: 720
      rate_limit_per_minute: 100
      csrf_enabled: true
      secure_cookies: false
    admin_email: "admin@alpha.com"
    is_active: true

  - name: "Project Beta"
    domain: "beta.org"
    settings:
      otp_enabled: false
      session_timeout_minutes: 1440
      rate_limit_per_minute: 60
      csrf_enabled: true
      secure_cookies: false
    admin_email: "admin@beta.org"
    is_active: true

  - name: "Project Gamma"
    domain: "localhost:3000"
    settings:
      otp_enabled: true
      session_timeout_minutes: 480
      rate_limit_per_minute: 150
      csrf_enabled: true
      secure_cookies: false
    admin_email: "admin@localhost"
    is_active: true
